apiVersion: v1
kind: Service
metadata:
  name: food-server
spec:
  selector:
    app: food-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # or "NodePort" if you're running locally with Minikube or kind
